apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
  labels:
    app: test-app
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello-world
              image: docker.io/hello-world
