#!/usr/bin/env bash
#
# Note: this does seems to work, but requires a log out/log in cycle to take
# effect.

set -o errexit
set -o nounset
set -o pipefail

defaults write -globalDomain AppleInterfaceStyleSwitchesAutomatically -bool true # Dark mode - Auto
