#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/.bin
"${SCRIPT_DIR}/macos-delete-service" 'com.apple.finder - Finder/Open - open'
"${SCRIPT_DIR}/macos-disable-service" 'com.apple.FolderActionsSetup - Folder Actions Setup - openFilesFromPasteboard'
"${SCRIPT_DIR}/macos-disable-service" 'com.apple.Terminal - New Terminal Tab at Folder - newTerminalAtFolder'
"${SCRIPT_DIR}/macos-disable-service" 'com.apple.Terminal - New Terminal at Folder - newTerminalAtFolder'
"${SCRIPT_DIR}/macos-disable-service" 'com.apple.finder - Finder\/Reveal - reveal'
"${SCRIPT_DIR}/macos-disable-service" 'net.kovidgoyal.kitty - New kitty Tab Here - openTab'
"${SCRIPT_DIR}/macos-disable-service" 'org.hammerspoon.Hammerspoon - Send to Hammerspoon - processDockIconDraggedText'
