#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

# Disable sound at boot
sudo nvram SystemAudioVolume=" "

# See https://superuser.com/a/630985, `man pmset`
sudo pmset -b displaysleep 1  # 1 minute
sudo pmset -c displaysleep 10 # 10 minutes

sudo pmset -b sleep 30   # 30 mins
sudo pmset -c sleep 1080 # 18 hours

sudo pmset -a autopoweroff 1
sudo pmset -b autopoweroffdelay 21600  # 6 hours
sudo pmset -c autopoweroffdelay 172800 # 48 hours

sudo pmset -a standbydelayhigh 86400 # 24 hours
sudo pmset -a standbydelaylow 10800  # 3 hours
sudo pmset -a hibernatemode 3        # Full hibernate, memory still powered

sudo pmset -b lessbright 1
sudo pmset -c lessbright 0

sudo pmset -a powernap 0
sudo pmset -a proximitywake 0
sudo pmset -a ring 0
sudo pmset -a standby 1
sudo pmset -a womp 0

sudo pmset -a destroyfvkeyonstandby 1
