# See https://pre-commit.com for more information
---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-symlinks
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/Jarmos-san/shellcheck-precommit
      rev: v0.1.0
      hooks:
          - id: shellcheck-system
            types_or: [bash, sh]
            exclude: ^stow/common/.config/git/template/hooks/pre-commit
