# See https://pre-commit.com for more information
---
repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-symlinks
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-yaml
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.19.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/Jarmos-san/shellcheck-precommit
      rev: v0.2.0
      hooks:
          - id: shellcheck-system
            types_or: [bash, sh]
            exclude: ^stow/common/.config/git/template/hooks/pre-commit
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.21.2
      hooks:
          - id: gitleaks
    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v2.0.2
      hooks:
          - id: stylua-system
            exclude: ^stow/macos/.hammerspoon/hs/.*
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.2
      hooks:
          - id: ruff
          - id: ruff-format
    - repo: https://github.com/Calinou/pre-commit-luacheck
      rev: v1.0.0
      hooks:
          - id: luacheck
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.43.0
      hooks:
          - id: markdownlint
