#!/usr/bin/env bash

set -o errexit
set -o nounset

GIT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && git rev-parse --show-toplevel)"
# shellcheck disable=SC1091
source "${GIT_ROOT_DIR}/common.sh"

if ! command -v "normfn" >/dev/null 2>&1; then
    TEMPDIR=$(mktemp -d)

    # shellcheck disable=SC2154
    if [[ ${OSDISTRIBUTION} == "arch" ]]; then
        git clone https://github.com/andrewferrier/normfn.git "${TEMPDIR}"
        (cd "${TEMPDIR}" && make buildarch && sudo pacman -U --noconfirm ./*.pkg.tar.zst)
    elif [[ ${OSDISTRIBUTION} == "macos" ]]; then
        git clone https://github.com/andrewferrier/normfn.git "${TEMPDIR}"
        (cd "${TEMPDIR}" && make reinstall_osx_brew install_osx_finder)
    else
        git clone https://github.com/andrewferrier/normfn.git "${TEMPDIR}"
        (cd "${TEMPDIR}" && make builddeb && sudo dpkg -i normfn*.deb)
    fi
fi

if [[ ${OSDISTRIBUTION} == "macos" ]]; then
    if ! pip3 show coloredlogs >/dev/null; then
        pip3 install coloredlogs
    fi
fi
