#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if command -v pip3 &>/dev/null; then
    PIP=pip3
else
    PIP=pip
fi

PIP_INSTALL_UPGRADE="${PIP} install --user --upgrade"

$PIP_INSTALL_UPGRADE shell-gpt
