#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

NPM_PACKAGES=(
    "@prettier/plugin-xml"
    "bash-language-server"
    "dockerfile-language-server-nodejs"
    "json-language-server"
    "prettier"
    "prettier-plugin-toml"
    "remark-cli"
    "remark-frontmatter"
    "remark-gfm"
    "typescript"
    "typescript-language-server"
    "vim-language-server"
    # css, html, json
    "vscode-langservers-extracted"
    "yaml-language-server"
)

# shellcheck disable=SC2048,SC2086
npm install -g --omit=dev ${NPM_PACKAGES[*]}
# shellcheck disable=SC2048,SC2086
npm update -g --omit=dev ${NPM_PACKAGES[*]}
