#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

NPM_PACKAGES=("bash-language-server"
    "dockerfile-language-server-nodejs"
    "json-language-server"
    "prettier"
    "prettier-plugin-toml"
    "prettier-plugin-xml"
    "remark-cli"
    "remark-frontmatter"
    "remark-gfm"
    "typescript"
    "typescript-language-server"
    "vim-language-server"
    # css, html, json
    "vscode-langservers-extracted"
    "yaml-language-server")

npm install -g --production ${NPM_PACKAGES[*]}
npm update -g --production ${NPM_PACKAGES[*]}
