#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

GIT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && git rev-parse --show-toplevel)"
# shellcheck disable=SC1091
source "${GIT_ROOT_DIR}/common.sh"

if [[ ${OSDISTRIBUTION:?} == "arch" ]]; then
    PIPX="pipx install --include-deps"

    pacaur -S --noconfirm basedpyright-git
    ${PIPX} gitlint
    ${PIPX} sqlfluff
elif [[ ${OSDISTRIBUTION:?} == "macos" ]]; then
    PIPX="pipx"

    ${PIPX} install gitlint --include-deps || ${PIPX} upgrade gitlint
    ${PIPX} install sqlfluff || ${PIPX} upgrade sqlfluff
    ${PIPX} install ruff || ${PIPX} upgrade ruff
    ${PIPX} install basedpyright || ${PIPX} upgrade basedpyright
else
    PIPX="pipx"

    # All other packages installed via package manager
    ${PIPX} install ruff || ${PIPX} upgrade ruff
    ${PIPX} install basedpyright || ${PIPX} upgrade basedpyright
fi
