#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

GIT_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && git rev-parse --show-toplevel)"
# shellcheck disable=SC1091
source "${GIT_ROOT_DIR}/common.sh"

pipx_install_or_upgrade() {
    local PACKAGE=$1
    shift
    local ARGS=("$@")

    if pipx list | grep -q "$PACKAGE"; then
        # shellcheck disable=SC2048,SC2086
        pipx upgrade "$PACKAGE" ${ARGS[*]}
    else
        # shellcheck disable=SC2048,SC2086
        pipx install "$PACKAGE" ${ARGS[*]}
    fi
}

pipx_install_or_upgrade mdformat
pipx inject mdformat mdformat-gfm mdformat-frontmatter mdformat-footnote

if [[ ${OSDISTRIBUTION:?} == "arch" ]]; then
    pacaur -S --noconfirm basedpyright
    pipx_install_or_upgrade gitlint --include-deps
    pipx_install_or_upgrade sqlfluff --include-deps
elif [[ ${OSDISTRIBUTION:?} == "macos" ]]; then
    # All packages install via Homebrew
    exit
else
    # All other packages installed via package manager
    pipx_install_or_upgrade ruff
    pipx_install_or_upgrade basedpyright
fi
