#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

LOCAL_BIN="${HOME}/.local/bin"

if [[ $(uname -s || true) == Linux* ]]; then
    rm -rf "${LOCAL_BIN}"/lua-language-server*/
    eget --to "${LOCAL_BIN}" LuaLS/lua-language-server --download-only --asset=^musl
    cd "${LOCAL_BIN}"
    aunpack --quiet lua-language-server*.tar.gz && rm lua-language-server*.tar.gz
    mv lua-language-server-*/ lua-language-server
else
    # MacOS
    eget --to "${LOCAL_BIN}" redhat-developer/vscode-xml --asset=lemminx --asset=aarch
    mv "${LOCAL_BIN}"/lemminx* "${LOCAL_BIN}"/lemminx
fi

eget --to "${LOCAL_BIN}" hadolint/hadolint --upgrade-only
eget --to "${LOCAL_BIN}" opentofu/tofu-ls --upgrade-only
