#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

DISTRIBUTION=$(uname -s)

if [[ $DISTRIBUTION != 'Darwin' ]]; then
    DISTRIBUTION=$(cat /etc/*-release | grep ^ID | sed 's/.*=//')
fi

if [[ $DISTRIBUTION == 'arch' ]]; then
    PIPX="pipx install --include-deps"

    sudo pacman -S --noconfirm python-black python-pipx
    ${PIPX} gitlint
    ${PIPX} sqlfluff
else
    if command -v pip3 &>/dev/null; then
        PIP=pip3
    else
        PIP=pip
    fi

    PIP_INSTALL_UPGRADE="${PIP} install --user --upgrade"

    ${PIP_INSTALL_UPGRADE} black
    ${PIP_INSTALL_UPGRADE} gitlint
    ${PIP_INSTALL_UPGRADE} sqlfluff
fi
