#!/usr/bin/env bash

LOCAL_BIN=${HOME}/.local/bin

curl --silent --location https://github.com/Narasimha1997/fake-sms/blob/main/bin/fake-sms?raw=true >"${LOCAL_BIN}/fake-sms"
curl --silent --location https://git.io/tmpmail >"${LOCAL_BIN}/tmpmail"

if [[ ! -x /usr/bin/eget ]]; then
    curl --silent --location https://zyedidia.github.io/eget.sh >"/tmp/eget.sh"
    echo "0e64b8a3c13f531da005096cc364ac77835bda54276fedef6c62f3dbdc1ee919 /tmp/eget.sh" | sha256sum --check --status
    mv /tmp/eget.sh "${LOCAL_BIN}/eget"
    chmod +x "${LOCAL_BIN}/eget"
fi
