#!/usr/bin/env bash

BASEDIR=${HOME}/.config/systemd/user

# shellcheck disable=SC2154
DEFAULT_DIR="${XDG_CONFIG_HOME}/systemd/user/default.target.wants"
TIMERS_DIR="${XDG_CONFIG_HOME}/systemd/user/timers.target.wants"

mkdir -p "${DEFAULT_DIR}" "${TIMERS_DIR}"

if [[ -h $DEFAULT_DIR ]]; then
    echo >&2 "${DEFAULT_DIR} cannot be a symlink."
    exit 1
fi

if [[ -h $TIMERS_DIR ]]; then
    echo >&2 "${TIMERS_DIR} cannot be a symlink."
    exit 1
fi

if [[ -d "${BASEDIR}" ]]; then
    for UNIT in "${BASEDIR}"/*.service; do
        UNIT_NOEXT="${UNIT%.*}"

        if [[ -f $UNIT_NOEXT.timer ]]; then
            echo "Enabling timer $UNIT_NOEXT.timer"
            systemctl --user enable --now "$UNIT_NOEXT.timer"
        elif [[ ! $UNIT_NOEXT =~ "@" ]]; then
            echo "Enabling service $UNIT_NOEXT.service"
            systemctl --user enable --now "$UNIT_NOEXT.service"
        else
            echo "Ignoring service $UNIT_NOEXT.service"
        fi
    done
fi
