#!/usr/bin/env bash

# See https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

set -o errexit
set -o nounset
set -o pipefail

yabai -m config window_border       off
yabai -m config window_opacity      off
yabai -m config window_placement    second_child
yabai -m config window_shadow       on
yabai -m config window_topmost      on # floating windows are always on top (default: off)
yabai -m config auto_balance        on

yabai -m config layout              bsp
yabai -m config top_padding         0
yabai -m config bottom_padding      0
yabai -m config left_padding        0
yabai -m config right_padding       0
yabai -m config window_gap          0

yabai -m rule --add app="AnyConnect" manage=off
yabai -m rule --add app="GIMP" manage=off
yabai -m rule --add app="WhatsApp" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

yabai -m rule --add title="^vimpc$" manage=off
yabai -m rule --add title="^file-list.*$" manage=off

yabai -m signal --add event=space_changed action="open -g 'swiftbar://refreshPlugin?name=yabai_space'"
yabai -m signal --add event=window_focused action="open -g 'swiftbar://refreshPlugin?name=yabai_space'"

# This signal is for when you move a space in Mission Control
yabai -m signal --add event=mission_control_exit action="open -g 'swiftbar://refreshPlugin?name=yabai_space'"
