#!/usr/bin/env bash

set -o errexit
set -o noglob
set -o nounset
set -o pipefail

shopt -s inherit_errexit

gsettings set de.wagnermartin.Plattenalbum show-audio-format false
gsettings set de.wagnermartin.Plattenalbum sort-albums-by-year true
gsettings set de.wagnermartin.Plattenalbum stop-on-quit false
