#!/usr/bin/env bash

readonly PLISTBUDDY=/usr/libexec/PlistBuddy

SERVICE_IDENTIFIER=$1

${PLISTBUDDY} -c "Print :NSServicesStatus:'${SERVICE_IDENTIFIER}':enabled_context_menu" ~/Library/Preferences/pbs.plist >/dev/null 2>&1 && rc=$? || rc=$?

if [[ ${rc} -eq 0 ]]; then
    ${PLISTBUDDY} -c "Set :NSServicesStatus:'${SERVICE_IDENTIFIER}':enabled_context_menu false" ~/Library/Preferences/pbs.plist
    ${PLISTBUDDY} -c "Set :NSServicesStatus:'${SERVICE_IDENTIFIER}':enabled_services_menu false" ~/Library/Preferences/pbs.plist
else
    echo "WARNING: service ${SERVICE_IDENTIFIER} not present."
fi
