#!/usr/bin/env sh

set -o errexit
set -o noglob
set -o nounset

if command -v codium &> /dev/null; then
    CODECMD=codium
else
    CODECMD=code

    $CODECMD --install-extension ms-vsliveshare.vsliveshare
fi

$CODECMD --install-extension hashicorp.terraform
$CODECMD --install-extension ms-python.python
$CODECMD --install-extension vscodevim.vim
