#!/usr/bin/env bash

set -o errexit
set -o noglob
set -o nounset

if [[ ${OSTYPE} == darwin* ]]; then
    code --install-extension ms-vsliveshare.vsliveshare
fi

code --install-extension hashicorp.terraform
code --install-extension ms-python.python
code --install-extension vscodevim.vim
