#!/usr/bin/env bash

if [[ $(uname -s) == Linux* ]]; then
    FIND_CMD="find"
    BASE_DIR="${HOME}/.librewolf/"
else
    FIND_CMD="gfind"
    BASE_DIR="${HOME}/Library/Application Support/librewolf/Profiles"
fi

PROFILE_DIR=$(${FIND_CMD} "${BASE_DIR}" -maxdepth 1 -type d -regextype egrep -regex '.*[a-zA-Z0-9]+.default-(release|default|esr)')

mkdir -p "${PROFILE_DIR}/chrome"

ln -sf "${HOME}/.librewolf/userContent.css" "${PROFILE_DIR}/chrome/userContent.css"
