#!/usr/bin/env bash

# shellcheck disable=SC2312
if [[ $(uname -s) == Linux* ]]; then
    FIND_CMD="find"
    BASE_DIR="${HOME}/.librewolf/"
else
    FIND_CMD="gfind"
    BASE_DIR="${HOME}/Library/Application Support/librewolf/Profiles"
fi

PROFILE_DIRS=$(${FIND_CMD} "${BASE_DIR}" -maxdepth 1 -type d -regextype egrep -regex '.*[a-zA-Z0-9]+.default')

while IFS= read -r PROFILE_DIR; do
    mkdir -p "${PROFILE_DIR}/chrome"
    ln -sf "${HOME}/.librewolf/userContent.css" "${PROFILE_DIR}/chrome/userContent.css"
done <<<"$PROFILE_DIRS"
