#!/usr/bin/env bash

set -o errexit
set -o nounset

export TMUX_PLUGIN_MANAGER_PATH=${TMUX_PLUGIN_MANAGER_PATH:-${XDG_DATA_HOME}/.tmux/plugins}

if [[ ! -d ${TMUX_PLUGIN_MANAGER_PATH}/tpm ]]; then
    git clone --quiet --depth 1 https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"
else
    (cd "${TMUX_PLUGIN_MANAGER_PATH}/tpm" &&
        git checkout master &&
        git fetch --all &&
        git reset --hard origin/master &&
        git clean -xf)
fi

# This is necessary if not running from within tmux.
BIN=${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin

"${BIN}/install_plugins"
"${BIN}/update_plugins" all
"${BIN}/clean_plugins"
