#!/usr/bin/env bash

set -o errexit
set -o nounset

if [[ ! -d ${HOME}/.tmux/plugins/tpm ]]; then
    git clone --quiet --depth 1 https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"
else
    (cd "${HOME}/.tmux/plugins/tpm" &&
        git checkout master &&
        git fetch --all &&
        git reset --hard origin/master &&
        git clean -xf)
fi

# This is necessary if not running from within tmux.
export TMUX_PLUGIN_MANAGER_PATH=${TMUX_PLUGIN_MANAGER_PATH:-${HOME}/.tmux/plugins}
BIN=${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin

${BIN}/install_plugins
${BIN}/update_plugins all
${BIN}/clean_plugins
