#!/usr/bin/env bash

# Keyboard
defaults write -globalDomain InitialKeyRepeat -int 10
defaults write -globalDomain KeyRepeat -int 1

defaults write com.apple.finder FXPreferredViewStyle Nlsv
defaults write com.apple.finder FXRemoveOldTrashItems -int 1 # Delete items from Trash/Bin after 30 days

killall Finder
