#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
ROOT_DIR=${1:-${SCRIPT_DIR}/..}

for directory in "${ROOT_DIR}"/if-command/*; do
    COMMAND=$(basename "$directory")

    if command -v "$COMMAND" >/dev/null; then
        stow --verbose --dir="${ROOT_DIR}/if-command" --target="${HOME}" --stow "$COMMAND"

        AFTER_SCRIPT=$(realpath "${ROOT_DIR}/if-command-after")

        if [ -d "${AFTER_SCRIPT}" ]; then
            AFTER_SCRIPT="${AFTER_SCRIPT}/${COMMAND}"

            if [ -f "${AFTER_SCRIPT}" ]; then
                printf "Running %s..." "${AFTER_SCRIPT}"
                echo ""
                ${AFTER_SCRIPT}
                echo "${AFTER_SCRIPT} complete."
            fi
        fi
    fi
done
