#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DOTFILES_DIR=${SCRIPT_DIR}/..

for directory in "${DOTFILES_DIR}"/if-command/*; do
    COMMAND=$(basename "$directory")

    if command -v "$COMMAND" >/dev/null; then
        stow --verbose --dir="${DOTFILES_DIR}/if-command" --target="${HOME}" --stow "$COMMAND"

        AFTER_SCRIPT=$(realpath "${DOTFILES_DIR}/if-command-after/${COMMAND}")
        if [ -f "${AFTER_SCRIPT}" ]; then
            printf "Running %s..." "${AFTER_SCRIPT}"
            echo ""
            ${AFTER_SCRIPT}
            echo "${AFTER_SCRIPT} complete."
        fi
    fi
done
