#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

NORMAL=$(tput sgr0)
GREY=$(tput setaf 7)

ROOT_DIR=$(realpath "${1:?Root dir not provided}")

for file_or_dir in "${ROOT_DIR}"/*; do
    if [[ -f $file_or_dir ]]; then
        printf "${GREY}Running %s...${NORMAL}\n" "${file_or_dir}"
        ${file_or_dir}
        printf "${GREY}${file_or_dir} complete.${NORMAL}\n\n"
    fi
done
