#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

NORMAL=$(tput sgr0)
GREY=$(tput setaf 7)

ROOT_DIR=$(realpath "${1:?Root dir not provided}")

for directory in "${ROOT_DIR}"/*; do
    COMMAND=$(basename "$directory")

    if command -v "$COMMAND" >/dev/null; then
        AFTER_SCRIPT=$(realpath "${ROOT_DIR}")

        if [[ -d "${AFTER_SCRIPT}" ]]; then
            AFTER_SCRIPT="${AFTER_SCRIPT}/${COMMAND}"

            if [[ -f "${AFTER_SCRIPT}" ]]; then
                printf "${GREY}Running %s...${NORMAL}\n" "${AFTER_SCRIPT}"
                ${AFTER_SCRIPT}
                printf "%b${AFTER_SCRIPT} complete.%b\n\n" "${GREY}" "${NORMAL}"
            fi
        fi
    fi
done
