#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

NORMAL=$(tput sgr0)
GREY=$(tput setaf 7)

ROOT_DIR=$(realpath "${1:?Root dir not provided}")

for file in "${ROOT_DIR}"/*; do
    printf "${GREY}Running %s...${NORMAL}\n" "${file}"
    ${file}
    printf "${GREY}${file} complete.${NORMAL}\n"
done
