#!/bin/bash

set -o nounset
set -o pipefail

# For some reason this is required to make special characters like @ work with
# xdotool, even though setxkbmap -verbose shows the same keymap anyway. See
# https://stackoverflow.com/a/36480692/27641.
setxkbmap gb

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
XRESOURCES_FILE=$XDG_CONFIG_HOME/X11/.Xresources
[[ -f $XRESOURCES_FILE ]] && xrdb -merge -I"${HOME}" "$XRESOURCES_FILE"

xset s 60 60
xscreensaver -no-splash &
xautolock -time 20 -locker "${HOME}/.local/bin/linux/suspend-if-no-ac" &

redshift -v | logger -t "${USER}-redshift" &
unclutter --ignore-scrolling --jitter 10 --fork
variety -v | logger -t "${USER}-variety" &
bato &
dex --autostart --environment i3
xfsettingsd &

# Automatically synchronize PRIMARY and CLIPBOARD
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Set audio volume to 0
start-pulseaudio-x11
pactl set-sink-volume @DEFAULT_SINK@ 0

# Turn off console beep
xset b off

# Turn off mute keyboard light
echo 0 >/sys/class/leds/platform::micmute/brightness

# Disable touchscreen/Trackpoint
xinput disable "Raydium Corporation Raydium Touch System"
xinput disable "TPPS/2 Elan TrackPoint"

rfkill block bluetooth
rfkill block wwan

export TERMCMD=kitty
export BROWSER=librewolf
export OPENER=$HOME/.local/bin/common-dotfiles/open-file

# https://wiki.archlinux.org/title/HiDPI#X_Resources

# Affects KeepassXC
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# This is adapted from the default /etc/X11/xinit/xinitrc, which this file
# overrides
if [[ -d /etc/X11/xinit/xinitrc.d ]]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        # shellcheck disable=SC1090
        [[ -x "$f" ]] && . "$f"
    done
    unset f
fi

exec i3
