#!/usr/bin/env bash

set -o errexit
set -o nounset

SCRIPT_NAME=$(basename "$0")

log() {
    echo "$*" | systemd-cat --identifier="${SCRIPT_NAME}"
}

log "Reloading variety..."
variety --next || true
variety --prev || true

if xrandr | grep " connected " | awk '{ print$1 }' | grep eDP1 > /dev/null; then
    log "Changing screen blanking timeout for laptop..."
    xset s 60 60
else
    log "Changing screen blanking timeout for external..."
    xset s 3600 3600
fi
