#!/usr/bin/env bash

set -o errexit
set -o nounset

SCRIPT_NAME=$(basename "$0")

log() {
    echo "$*" | systemd-cat --identifier="${SCRIPT_NAME}"
}

log "Reloading variety..."
# Seems like sometimes these hang, hence timeout
timeout 10 variety --next || true
timeout 10 variety --prev || true
