enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
ctrl-alt-cmd-enter = 'exec-and-forget open -n /Applications/kitty.app'

ctrl-alt-cmd-left = 'focus left'
ctrl-alt-cmd-down = 'focus down'
ctrl-alt-cmd-up = 'focus up'
ctrl-alt-cmd-right = 'focus right'

ctrl-alt-cmd-shift-left = 'move left'
ctrl-alt-cmd-shift-down = 'move down'
ctrl-alt-cmd-shift-up = 'move up'
ctrl-alt-cmd-shift-right = 'move right'

ctrl-alt-cmd-h = 'split horizontal'
ctrl-alt-cmd-v = 'split vertical'

ctrl-alt-cmd-f = 'fullscreen'

ctrl-alt-cmd-w = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

ctrl-alt-cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

ctrl-alt-cmd-1 = 'workspace 1'
ctrl-alt-cmd-2 = 'workspace 2'
ctrl-alt-cmd-3 = 'workspace 3'
ctrl-alt-cmd-4 = 'workspace 4'
ctrl-alt-cmd-5 = 'workspace 5'
ctrl-alt-cmd-6 = 'workspace 6'
ctrl-alt-cmd-7 = 'workspace 7'
ctrl-alt-cmd-8 = 'workspace 8'
ctrl-alt-cmd-9 = 'workspace 9'

ctrl-alt-cmd-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-cmd-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-cmd-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-cmd-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-cmd-shift-5 = 'move-node-to-workspace 5'
ctrl-alt-cmd-shift-6 = 'move-node-to-workspace 6'
ctrl-alt-cmd-shift-7 = 'move-node-to-workspace 7'
ctrl-alt-cmd-shift-8 = 'move-node-to-workspace 8'
ctrl-alt-cmd-shift-9 = 'move-node-to-workspace 9'

ctrl-right = 'workspace next'
ctrl-left = 'workspace prev'

ctrl-alt-cmd-shift-c = 'reload-config'
