.PHONY: pkgs

pkgs:
	apk info git || apk add git
	apk info mandoc || apk add mandoc
	apk info man-pages || apk add man-pages
	apk info neovim || apk add neovim
	apk info openssh-client-default || apk add openssh-client-default
	apk info tig || apk add tig
