# See https://pre-commit.com for more information
---
repos:
    # General

    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-shebang-scripts-are-executable
          - id: check-symlinks
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-yaml
    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
      rev: 3.0.3
      hooks:
          - id: editorconfig-checker
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.18.4
      hooks:
          - id: gitleaks
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint

    # Language-specific

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.17.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.3
      hooks:
          - id: ruff
          - id: ruff-format
    - repo: https://github.com/Jarmos-san/shellcheck-precommit
      rev: v0.2.0
      hooks:
          - id: shellcheck-system
            types_or: [bash, sh]
    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.20.0
      hooks:
          - id: stylua-system
