---
all:
  hosts:
    host1:
      ansible_ssh_host: 1.2.3.4
    host2:
      ansible_ssh_host: 5.6.7.8
  children:
    servergroup1:
      hosts:
        host3:
          ansible_ssh_host: 9.10.11.12