#!/usr/bin/env python

# uv-based shebang
# {{{
#!/usr/bin/env -S uv run --script
# vim: set ft=python:
#
# /// script
# dependencies = [
#     "abc",
#     "xyz"
# ]
# ///
# }}}

import argparse
import logging
import sys

# Logging
# {{{
logger = logging.getLogger("my-script")
logger.propagate = False
logger.setLevel(logging.WARNING)

syserr_handler = logging.StreamHandler(stream=sys.stderr)
syserr_handler.setLevel(logging.WARNING)
syserr_handler.setFormatter(logging.Formatter("my-script: %(levelname)s: %(message)s"))
logger.addHandler(syserr_handler)
# }}}

# Argument Parsing
# {{{
parser = argparse.ArgumentParser()
parser.add_argument("--argument_one", default="value")
parser.add_argument("--argument_two", required=True)
args = parser.parse_args()
# }}}


def main() -> None:
    # Code goes here
    pass


if __name__ == "__main__":
    main()
