tap "homebrew/cask-fonts"
tap "buo/cask-upgrade" # provides 'brew cu' cask upgrade command

brew "ansible-language-server"
brew "ansible-lint"
brew "aria2"
brew "atool"
brew "automake"
brew "basedpyright"
brew "bash" # for improved performance
brew "bat"
brew "bitwarden-cli"
brew "blueutil" # for Hammerspoon
brew "borgbackup"
brew "coreutils"
brew "curl"
brew "defaultbrowser"
brew "direnv"
brew "docx2txt" # for scope.sh
brew "duti"
brew "eget"
brew "entr"
brew "exiftool" # for scope.sh
brew "eza"
brew "fd"
brew "fdupes"
brew "figlet"
brew "findutils"
brew "fzf"
brew "git"
brew "git-delta"
brew "gitlint"
brew "grep" # for file-list
brew "gzip"
brew "hexedit"
brew "httpie"
brew "hyperfine"
brew "iftop"
brew "isync"
brew "jq"
brew "latexindent" # for NeoVim
brew "lf"
brew "libqalculate" # includes CLI
brew "lua-language-server"
brew "lua@5.3" # for lua-lsp
brew "luarocks"
brew "lzip"
brew "make" # GNU make with Mac OS is ancient
brew "markdownlint-cli"
brew "mas"
brew "moreutils" # isutf8 for Hammerspoon
brew "ncdu"
brew "neovim"
brew "ollama"
brew "pandoc" # for scope.sh
brew "poppler" # pdftotext for scope.sh
brew "pre-commit"
brew "pstree"
brew "pwgen"
brew "python3"
brew "ripgrep"
brew "ripgrep-all"
brew "rsync"
brew "ruff" # for neovim LSP
brew "selene"
brew "shellcheck" # to support bash-language-server
brew "shellharden"
brew "shfmt" # to support bash-language-server
brew "smudge/smudge/nightlight"
brew "sqlfluff"
brew "stow"
brew "stylua"
brew "terminal-notifier"
brew "texlab"
brew "tig"
brew "tmux"
brew "trash"
brew "uv"
brew "w3m"
brew "watch"
brew "wget"
brew "yq"
brew "zsh-lovers"

cask "MonitorControl"
cask "drawio"
cask "font-consolas-for-powerline" # for kitty
cask "hammerspoon"
cask "karabiner-elements"
cask "keepassxc"
cask "kitty"
cask "librewolf", args: { quarantine: false }
cask "notunes"
cask "platypus"
cask "podman-desktop"
cask "poe"
cask "visual-studio-code"
cask "whatsapp"

# vim: set filetype=ruby:
