#!/usr/bin/env bash

# Keyboard
defaults write -globalDomain InitialKeyRepeat -int 10
defaults write -globalDomain KeyRepeat -int 1

defaults write -globalDomain NSDocumentSaveNewDocumentsToCloud -bool false
defaults write -globalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write -globalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write com.apple.TextEdit RichText -int 0
defaults write com.apple.dock autohide -int 1
defaults write com.apple.finder AppleShowAllFiles -bool false
defaults write com.apple.finder FXPreferredViewStyle Nlsv
defaults write com.apple.finder FXRemoveOldTrashItems -int 1 # Delete items from Trash/Bin after 30 days
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool false
defaults write com.apple.finder ShowRecentTags -bool false
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool false
defaults write com.apple.iTunes DeviceBackupsDisabled -bool true
defaults write com.apple.iTunes dontAutomaticallySyncIPods -bool true
defaults write com.apple.safari IncludeDebugMenu -bool YES
defaults write org.pqrs.Karabiner isStatusbarEnable -bool false

killall Finder
