---
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  urlchecker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install urlchecker
      run: |
        python -m pip install urlchecker

    - name: Run urlchecker
      run: |
        urlchecker check \
          --branch main \
          --no-print \
          --file-types .md \
          --exclude-patterns docs.google.com \
          --retry-count 1 \
          --timeout 5 \
          .
